version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data sources
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez data
        columns:
          - name: PK
            tests:
              - unique
                 column_name "(orders_id||'_'||pdt_id)"

      - name: product
        identifier: raw_product
        description: product of greenweez data
        columns:
          - name: products_id
            tests:
              - not_null
              - unique
                  
      - name: ship
        identifier: raw_ship
        description: ship of greenweez data
        columns:
          - name: orders_id
            tests:
            - not_null
            - unique
                